export const RETRIEVE_POST = 'RETRIEVE_POST'

export const RETRIEVE_POST_SUCCESS = 'RETRIEVE_POST_SUCCESS'

export const RETRIEVE_POST_ERROR = 'RETRIEVE_POST_ERROR'

export const RETRIEVE_USER_INFO = 'RETRIEVE_USER_INFO'

export const RETRIEVE_USER_INFO_SUCCESS = 'RETRIEVE_USER_INFO_SUCCESS'

export const RETRIEVE_USER_INFO_ERROR = 'RETRIEVE_USER_INFO_ERROR'
